import type { UnlockableDefinition } from 'onboarding-tools';

export const DOCS_APP_ID = 'onboarding-tools-docs';
export const DOCS_EVENTS_KEY = 'docs-events';

export const definitions = [
  {
    id: 'welcome',
    activation: 'automatic',
    visibility: 'hidden',
    meta: {
      title: 'Welcome',
      description: 'Start the interactive documentation tour.',
      tags: ['getting-started'],
    },
    flow: {
      stage: 'Welcome',
      order: 10,
      route: '/',
      target: '[data-tour="welcome-hero"]',
      completionEvent: 'tour.started',
    },
    tutorial: { kind: 'none' },
  },
  {
    id: 'quickstart',
    activation: 'automatic',
    visibility: 'hidden',
    meta: {
      title: 'Quickstart',
      description: 'Mount the provider tree and run one unlockable definition.',
      tags: ['getting-started'],
    },
    unlocksOn: { kind: 'event', event: 'tour.started' },
    flow: {
      stage: 'Quickstart',
      order: 20,
      route: '/quickstart',
      target: '[data-tour="quickstart-playground"]',
      completionEvent: 'quickstart.run',
    },
    tutorial: { kind: 'none' },
  },
  {
    id: 'state-machine',
    activation: 'automatic',
    visibility: 'hidden',
    meta: {
      title: 'The state machine',
      description: 'Inspect the HIDDEN, ELIGIBLE, UNLOCKING, and UNLOCKED lifecycle.',
      tags: ['getting-started'],
    },
    unlocksOn: { kind: 'event', event: 'quickstart.run' },
    flow: {
      stage: 'The state machine',
      order: 30,
      route: '/concepts/state-machine',
      target: '[data-tour="state-machine-viz"]',
      completionEvent: 'state-machine.cycled',
    },
    tutorial: { kind: 'none' },
  },
  {
    id: 'criteria',
    activation: 'manual',
    visibility: 'hidden',
    meta: {
      title: 'Criteria DSL',
      description: 'Compose event, archetype, flag, and combinator criteria.',
      tags: ['concepts'],
    },
    unlocksOn: { kind: 'event', event: 'state-machine.cycled' },
    flow: {
      stage: 'Criteria DSL',
      order: 40,
      route: '/concepts/criteria',
      target: '[data-tour="criteria-editor"]',
      completionEvent: 'criteria.experimented',
    },
    tutorial: {
      title: 'Criteria DSL unlocked',
      body: 'This section is manual. Confirm the unlock to enter the criteria editor.',
      primaryActionLabel: 'Enter criteria',
      dismissActionLabel: 'Later',
    },
  },
  {
    id: 'overlays',
    activation: 'automatic',
    visibility: 'hidden',
    meta: {
      title: 'Tutorial overlays',
      description: 'Run the spotlight and coach-card tutorial engine against live DOM targets.',
      tags: ['concepts'],
    },
    unlocksOn: { kind: 'event', event: 'criteria.experimented' },
    flow: {
      stage: 'Tutorial overlays',
      order: 50,
      route: '/concepts/overlays',
      target: '[data-tour="mini-tour"]',
      completionEvent: 'tutorial.dismissed',
    },
    tutorial: { kind: 'none' },
  },
  {
    id: 'archetypes',
    activation: 'automatic',
    visibility: 'hidden',
    meta: {
      title: 'Archetypes & personalization',
      description: 'Switch user archetypes from the topbar and watch matching surfaces become eligible.',
      tags: ['concepts'],
    },
    unlocksOn: { kind: 'event', event: 'tutorial.dismissed' },
    flow: {
      stage: 'Archetypes & personalization',
      order: 60,
      route: '/concepts/archetypes',
      target: '[data-tour="archetype-showcase"]',
      completionEvent: 'archetype.experimented',
    },
    tutorial: { kind: 'none' },
  },
  {
    id: 'theming',
    activation: 'automatic',
    visibility: 'hidden',
    meta: {
      title: 'Theming',
      description: 'Tune onboarding overlay CSS tokens and preview the result.',
      tags: ['concepts'],
    },
    unlocksOn: { kind: 'event', event: 'archetype.experimented' },
    flow: {
      stage: 'Theming',
      order: 70,
      route: '/concepts/theming',
      target: '[data-tour="theme-token-playground"]',
      completionEvent: 'theme.tweaked',
    },
    tutorial: { kind: 'none' },
  },
  {
    id: 'storage',
    activation: 'automatic',
    visibility: 'hidden',
    meta: {
      title: 'Storage adapters',
      description: 'Compare localStorage, sessionStorage, and a mocked remote adapter.',
      tags: ['advanced'],
    },
    unlocksOn: { kind: 'flag', key: 'developer-mode', value: true },
    flow: {
      stage: 'Storage adapters',
      order: 80,
      route: '/advanced/storage',
      target: '[data-tour="storage-picker"]',
      completionEvent: 'storage.swapped',
    },
    tutorial: { kind: 'none' },
  },
  {
    id: 'resolvers',
    activation: 'manual',
    visibility: 'hidden',
    meta: {
      title: 'Resolvers & AI',
      description: 'Mock an async resolver returning UnlockDecision objects.',
      tags: ['advanced'],
    },
    unlocksOn: {
      all: [
        { kind: 'flag', key: 'developer-mode', value: true },
        { kind: 'event', event: 'tutorial.dismissed' },
      ],
    },
    flow: {
      stage: 'Resolvers & AI',
      order: 90,
      route: '/advanced/resolvers',
      target: '[data-tour="mock-llm-resolver"]',
      completionEvent: 'resolver.invoked',
    },
    tutorial: {
      title: 'Resolvers unlocked',
      body: 'Developer mode is on and the overlay tutorial is complete. Confirm to inspect resolver decisions.',
      primaryActionLabel: 'Open resolvers',
      dismissActionLabel: 'Later',
    },
  },
  {
    id: 'api-reference',
    activation: 'automatic',
    visibility: 'hidden',
    meta: {
      title: 'API reference',
      description: 'Scan the public React hooks, providers, and component entry points.',
      tags: ['advanced'],
    },
    unlocksOn: { kind: 'event', event: 'tutorial.dismissed' },
    flow: {
      stage: 'API reference',
      order: 100,
      route: '/api',
      target: '[data-tour="api-table"]',
      required: false,
    },
    tutorial: { kind: 'none' },
  },
  {
    id: 'recipes',
    activation: 'automatic',
    visibility: 'hidden',
    meta: {
      title: 'Recipes',
      description: 'Copy framework-specific integration recipes.',
      tags: ['deploy'],
    },
    flow: {
      stage: 'Recipes',
      order: 110,
      route: '/recipes',
      target: '[data-tour="recipe-tabs"]',
      required: false,
    },
    tutorial: { kind: 'none' },
  },
  {
    id: 'deploy',
    activation: 'automatic',
    visibility: 'hidden',
    meta: {
      title: 'Deploy',
      description: 'Understand the example deployment path on Vercel.',
      tags: ['deploy'],
    },
    flow: {
      stage: 'Deploy',
      order: 120,
      route: '/deploy',
      target: '[data-tour="deploy-panel"]',
      required: false,
    },
    tutorial: { kind: 'none' },
  },
] satisfies UnlockableDefinition[];
